### PR TITLE
Migrate to Jekyll

### PR DESCRIPTION
**Pull request by soulim**
I would like to suggest [Jekyll](http://jekyllrb.com) as a static site generator. I guess you already know that GitHub Pages support Jekyll by default.

I've converted current site into Jekyll. It looks and works completely the same, except content and presentation are separated. I think it much nicer to write content in Markdown than duplicate all HTML pages.

You could also find a couple of helpful scripts in `script` directory:
- `script/bootstrap` check and install all missing dependencies
- `script/server` runs local Jekyll server

I would be happy to get your feedback :smile:

### CODE REVIEW

**Comment by skade** [comment]
We had that discussion and it's not quite solved. The problem with Jekyll is that it is not particularly easy to set up (and I say that as a Ruby engineer) and we'd like to keep the barrier of entry low.

**Comment by soulim** [comment]
Ah! Probably I so got used to Jekyll and don't see problems anymore. I thought it would be easier for content contributors because they could write just text (Markdown) and don't worry about its presentation, and people who would like to improve presentation would think only about HTML, CSS, and etc.

So, feel free to close the pull request :wink:

**Comment by skade** [comment]
Sorry for being a bit court yesterday. I see the problem that we will need some kind of static site builder at some time (especially for navigation, footers, data-driven stuff, rss feed, etc.).

My experiences with Jekyll are subpar though, I even held a talk about it. ;)
http://www.rubyconfuruguay.org/en/editions/2014/sessions/ruby-through-the-crystal-ball

My perfect static site generator should be easy to set up on Windows and *NIX and use only one runtime system, be it node.js, io.js, ruby, python, PHP, I don't care ;).

Middleman might be an option, but I'm not sure.

**Comment by skade** [comment]
Closing in favor of #3, thanks for the effort and raising the topic so early.

**Comment by soulim** [comment]
No worries. I'm always happy to help :smile:

**Pull request closed without merging**
